### ISSUE TITLE
No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Models.ApplicationUser]'

### ISSUE THREAD

**Issue by a-a-k** [quicksln/LiteDB.Identity#4]
I'm using `LiteDB.Identity` in project based on SPA (Angular) template. I changed `Statup.cs` as it shown in readme. The error was thrown when I tried to access protected sources (via `[Authorize]` attribute).
What's going wrong?

**Comment by quicksln** [comment]
Hi @a-a-k 

Thank you for using LiteDB.Identity.

Could I kindly ask you to double check connection string configuration for LiteDB:
https://github.com/quicksln/LiteDB.Identity/blob/master/sample/LiteDB.Identity.Sample/appsettings.json 

Next, please check if all references have been added correctly to your project definition : 
https://github.com/quicksln/LiteDB.Identity/blob/master/sample/LiteDB.Identity.Sample/LiteDB.Identity.Sample.csproj

At the very end please double check Configure section of Startup.cs if contains :
```csharp
app.UseAuthentication();
app.UseAuthorization();
```

https://github.com/quicksln/LiteDB.Identity/blob/master/sample/LiteDB.Identity.Sample/Startup.cs

And let me know how it went.

Regards
Piotr

**Comment by a-a-k** [comment]
@quicksln thank you for your reply!
All things you mentioned are same.
Okay,  seems the problem is underlying deeper. I think it is in auth mechanisms which provided by SPA template. There IdentityServer and its stuff. Now I'm getting `Error: Could not load settings for 'App' at AuthorizeService.js`.

**Comment by quicksln** [comment]
Hello @a-a-k 

Thank you for additional information. Unfortunately, I did not have chance to try IdentityServer4 
with ASP.NET Identity over LiteDb.Identity. 

But according to IdentityServer4 documentation, in theory it should be possible to use both, please have a look on following links: 

https://docs.identityserver.io/en/release/reference/aspnet_identity.html
https://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html

Hope you find this helpful. 

Regards
Piotr

**Comment by a-a-k** [comment]
Hi, Piotr.
Looks like no deal with IdentityServer without EF is possible.
https://github.com/IdentityServer/IdentityServer4/issues/4667
