### ISSUE TITLE
Can't edit nor delete users with LiteDbIdentity the same way I do with Microsoft's Identity

### ISSUE THREAD

**Issue by DanielRodFT** [quicksln/LiteDB.Identity#8]
When trying to update or delete a user, the user passed to my controller's UpdateUser method doesn't have an ID, the id property is null. I'm using the same exact process with Microsoft own Identity and the ID does return. I don't know if theres something I'm doing wrong of updating doesn't work the same as with microsoft's identity. The object does exist in the database and has a working Id.

1. **User object passed to update method when Microsoft's identity (first picture):**

![image](https://github.com/quicksln/LiteDB.Identity/assets/149818912/d0c25fb7-346a-4cc1-b652-e56a587da6f3)

2. **Select query with the required Id:**

![image](https://github.com/quicksln/LiteDB.Identity/assets/149818912/e6244ab6-88e5-446b-9271-37e04f9a4e79)

**Comment by quicksln** [comment]
Hello @DanielRodFT 

One more time thank you for using LiteDb.Identity :) 

I have just verified this, and it is functioning as expected. After creating the user, a new ID is returned to the user instance. To be doubly sure, I have created a new unit test for it. Please refer to the screenshots below.

![s1](https://github.com/quicksln/LiteDB.Identity/assets/65227444/435b26ff-14c7-49a6-8121-68986b377423)

![s2a](https://github.com/quicksln/LiteDB.Identity/assets/65227444/15b6fe96-012b-4a84-8152-47bef456b83b)


Based on your screenshot, I assume this is a POST action for updating a user from an MVC form submission. 
Could you please double-check whether you are correctly storing the user.Id on the form after creation? 

Please see pseudo code below :

```
@using (Html.BeginForm("ActionName", "ControllerName", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.UserId)
    
    ...
}
```

Regards
Piotr

**Comment by DanielRodFT** [comment]
Thank you for your help. As you mentioned it was due to the MVC model binder not being able to recreate the Id from the url. I'm now able to edit and delete users. Thanks:)
